### ISSUE TITLE
Vuln patched on Windows 10 v21H2 Build 19044.1826

### ISSUE THREAD

**Issue by GetRektBoy724** [last-byte/RIPPL#1]
Vuln is patched on Windows 10 v21H2 Build 19044.1826, you can read more about it here.
https://github.com/itm4n/PPLdump/issues/12

**Comment by last-byte** [comment]
Which is exactly [the reason this has been open sourced](https://twitter.com/last0x00/status/1551274172474695686).

**Comment by GetRektBoy724** [comment]
> Which is exactly [the reason this has been open sourced](https://twitter.com/last0x00/status/1551274172474695686).

Ohh okay, I thought its open source in the first place, just like PPLDump :sweat_smile:
